-CTF, viết tắt của Capture The Flag, là một định dạng phổ biến cho các cuộc thi an ninh mạng. Tên này xuất phát từ tên tệp 'flag', nơi người tham gia phải tìm trên hệ thống mục tiêu - và nội dung của nó là những gì họ cần nộp làm câu trả lời.
-Trong hầu hết các Wargame và thử thách CTF, mục tiêu rõ ràng là tìm ra lá cờ bằng mọi cách.
