-Wargame là môi trường kiểm thử xâm nhập nơi các lỗ hỏng được thiết kế có chú đích tồn tại.
- Các loại trò chơi chiến tranh thường rơi vào các loại sau: pwnable (hack hệ thống), web, kỹ thuật đảo ngược (reversing), mật mã, pháp y và hỗn hợp (misc). 
